post 'ai_rewrite/rewrite', to: 'ai_rewrite#rewrite'
post 'ai_rewrite/rewrite_stream', to: 'ai_rewrite#rewrite_stream'
post 'ai_rewrite/save_version', to: 'ai_rewrite#save_version'
get 'ai_rewrite/get_version', to: 'ai_rewrite#get_version'
get 'ai_rewrite/list_versions', to: 'ai_rewrite#list_versions'
get 'ai_rewrite/settings', to: 'ai_rewrite#settings'
delete 'ai_rewrite/clear_versions', to: 'ai_rewrite#clear_versions'
post 'ai_rewrite/test_connection', to: 'ai_rewrite#test_connection'
post 'ai_rewrite/pull_ollama_model', to: 'ai_rewrite#pull_ollama_model'
get 'ai_rewrite/requests', to: 'ai_rewrite#requests'
get 'ai_rewrite/check_versions', to: 'ai_rewrite#check_versions'

# AI Chat Routes
post 'ai_chat/ask', to: 'ai_chat#ask'
get 'ai_chat/history', to: 'ai_chat#history'
post 'ai_chat/clear', to: 'ai_chat#clear'